let LOCALHOST = true,
	CONF_BASE_URL,
	CONF_DATABASE_NAME,
	CONF_DATABASE_USER,
	CONF_DATABASE_PASSWORD,
	CONF_DATABASE_HOST,
	CONF_DATABASE_DIALECT,
	CONF_SERVER_PORT
if (LOCALHOST) {
	CONF_BASE_URL = "http://localhost:" + CONF_SERVER_PORT
	CONF_DATABASE_NAME = "ferafox62"
	CONF_DATABASE_USER = "ferafox62"
	CONF_DATABASE_PASSWORD = "194280aa"
	CONF_DATABASE_HOST = "mysql.ferafox.com"
	CONF_DATABASE_DIALECT = "mysql"
	CONF_SERVER_PORT = 3000
} else {
	CONF_BASE_URL = "http://localhost:" + CONF_SERVER_PORT
	CONF_DATABASE_NAME = "app_producao"
	CONF_DATABASE_USER = "sa"
	CONF_DATABASE_PASSWORD = "Templat3"
	CONF_DATABASE_HOST = "192.168.2.96"
	CONF_DATABASE_DIALECT = "mssql"
	CONF_SERVER_PORT = 4995
}
let CONF_VIEW_WEB = "themes/web/pages/",
	CONF_LAYOUT_WEB = "themes/web/",
	CONF_VIEW_APP = "themes/app/modules/",
	CONF_LAYOUT_APP = "themes/app/"

module.exports = {
	CONF_DATABASE_NAME,
	CONF_DATABASE_USER,
	CONF_DATABASE_PASSWORD,
	CONF_DATABASE_HOST,
	CONF_DATABASE_DIALECT,
	CONF_SERVER_PORT,
	CONF_VIEW_WEB,
	CONF_LAYOUT_WEB,
	CONF_VIEW_APP,
	CONF_LAYOUT_APP,
	CONF_BASE_URL
}
